#!/bin/bash
# Run the container in the current directory.

. ../../../libs/container.sh

internalModelPath="/opt/stable-diffusion-webui/models"

checkModelPath

set -x
docker run --gpus all -p "$port:$port" -v "$modelPath:$internalModelPath" "$containerName"
