#!/bin/bash
# Move external stuff to be ready to be exported.
# Why: We want these directories to be mounted from outside so that they can persist locally between runs.

externalThings="/workspace /home"

for externalThing in $externalThings; do
    cd "$externalThing"
    if [ ! -e .exported ]; then
        cp -rpv "$externalThing".moved/* .
        cp -rpv "$externalThing".moved/.??* . || true
        touch .exported
    fi
done
